stages:
  - build
  - test

variables:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_GENERATOR: Ninja

.default_build: &default_build
  image: ubuntu:24.04
  before_script:
    - chmod +x scripts/setup-machine.sh scripts/ci-local.sh
    - ./scripts/setup-machine.sh --ci

native-gcc-build:
  <<: *default_build
  stage: build
  script:
    - ./scripts/ci-local.sh --ci --preset native-gcc-release --build

native-clang-build:
  <<: *default_build
  stage: build
  script:
    - ./scripts/ci-local.sh --ci --preset native-clang-release --build

arm-linux-eabihf-gcc-build:
  <<: *default_build
  stage: build
  script:
    - ./scripts/ci-local.sh --ci --preset arm-linux-eabihf-gcc-release --build

arm-linux-eabihf-clang-build:
  <<: *default_build
  stage: build
  script:
    - ./scripts/ci-local.sh --ci --preset arm-linux-eabihf-clang-release --build

arm64-linux-gcc-build:
  <<: *default_build
  stage: build
  script:
    - ./scripts/ci-local.sh --ci --preset arm64-linux-gcc-release --build

arm64-linux-clang-build:
  <<: *default_build
  stage: build
  script:
    - ./scripts/ci-local.sh --ci --preset arm64-linux-clang-release --build

arm-none-eabi-gcc-build:
  <<: *default_build
  stage: build
  script:
    - ./scripts/ci-local.sh --ci --preset arm-none-eabi-gcc-debug --build

arm-none-eabi-clang-build:
  <<: *default_build
  stage: build
  script:
    - ./scripts/ci-local.sh --ci --preset arm-none-eabi-clang-debug --build

unit-tests:
  <<: *default_build
  stage: test
  script:
    - ./scripts/ci-local.sh --ci --preset native-gcc-debug --build --test --ctest
  only:
    - branches
