if(NOT DEFINED TARGET_ARCH)
    if(DEFINED CMAKE_C_COMPILER)
        if(CMAKE_C_COMPILER MATCHES ".*arm.*linux.*gnueabihf.*")
            set(TARGET_ARCH arm-linux-eabihf CACHE STRING "Target architecture inferred from compiler" FORCE)
        elseif(CMAKE_C_COMPILER MATCHES ".*aarch64.*linux.*gnu.*")
            set(TARGET_ARCH arm64-linux CACHE STRING "Target architecture inferred from compiler" FORCE)
        elseif(CMAKE_C_COMPILER MATCHES ".*arm-none-eabi.*")
            set(TARGET_ARCH arm-none-eabi CACHE STRING "Target architecture inferred from compiler" FORCE)
        endif()
    endif()
    if(NOT DEFINED TARGET_ARCH)
        if(DEFINED CMAKE_C_COMPILER_TARGET)
            if(CMAKE_C_COMPILER_TARGET MATCHES "arm.*linux.*gnueabihf")
                set(TARGET_ARCH arm-linux-eabihf CACHE STRING "Target architecture inferred from compiler target" FORCE)
            elseif(CMAKE_C_COMPILER_TARGET MATCHES "aarch64.*linux.*gnu")
                set(TARGET_ARCH arm64-linux CACHE STRING "Target architecture inferred from compiler target" FORCE)
            elseif(CMAKE_C_COMPILER_TARGET STREQUAL "arm-none-eabi")
                set(TARGET_ARCH arm-none-eabi CACHE STRING "Target architecture inferred from compiler target" FORCE)
            endif()
        endif()
    endif()
    if(NOT DEFINED TARGET_ARCH AND DEFINED ENV{TARGET_ARCH})
        set(TARGET_ARCH $ENV{TARGET_ARCH} CACHE STRING "Target architecture from environment" FORCE)
    endif()
endif()

if(NOT DEFINED TARGET_ARCH)
    message(FATAL_ERROR "TARGET_ARCH must be set when using CMakeToolchain.cmake")
endif()

if(TARGET_ARCH STREQUAL "arm-none-eabi")
    include("${CMAKE_CURRENT_LIST_DIR}/ToolchainArmNoneEabi.cmake")
elseif(TARGET_ARCH STREQUAL "arm-linux-eabihf")
    include("${CMAKE_CURRENT_LIST_DIR}/ToolchainArmLinuxEabihf.cmake")
elseif(TARGET_ARCH STREQUAL "arm64-linux")
    include("${CMAKE_CURRENT_LIST_DIR}/ToolchainArm64Linux.cmake")
else()
    message(FATAL_ERROR "Unsupported TARGET_ARCH: ${TARGET_ARCH}")
endif()
