# Project-wide compiler options and warning sets
if(MSVC)
    set(CPP_TEMPLATE_WARNINGS
        /W4
        /permissive-
        /EHsc
        /WX
    )
else()
    set(CPP_TEMPLATE_WARNINGS
        -Wall
        -Wextra
        -Wpedantic
        -Wconversion
        -Wshadow
        -Wformat=2
        -Werror
    )
endif()
