# Toolchain for ARM Linux with hard-float ABI
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
if(NOT DEFINED CMAKE_C_COMPILER)
    set(CMAKE_C_COMPILER arm-none-linux-gnueabihf-gcc)
endif()
if(NOT DEFINED CMAKE_CXX_COMPILER)
    set(CMAKE_CXX_COMPILER arm-none-linux-gnueabihf-g++)
endif()
if(CMAKE_C_COMPILER MATCHES "clang")
    if(NOT DEFINED CMAKE_C_COMPILER_TARGET)
        set(CMAKE_C_COMPILER_TARGET arm-none-linux-gnueabihf)
    endif()
endif()
if(CMAKE_CXX_COMPILER MATCHES "clang")
    if(NOT DEFINED CMAKE_CXX_COMPILER_TARGET)
        set(CMAKE_CXX_COMPILER_TARGET arm-none-linux-gnueabihf)
    endif()
endif()
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
