# Toolchain for bare-metal Cortex-M / arm-none-eabi
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)
if(NOT DEFINED CMAKE_C_COMPILER)
    set(CMAKE_C_COMPILER arm-none-eabi-gcc)
endif()
if(NOT DEFINED CMAKE_CXX_COMPILER)
    set(CMAKE_CXX_COMPILER arm-none-eabi-g++)
endif()
if(NOT DEFINED CMAKE_ASM_COMPILER)
    set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
endif()
if(CMAKE_C_COMPILER MATCHES "clang")
    if(NOT DEFINED CMAKE_C_COMPILER_TARGET)
        set(CMAKE_C_COMPILER_TARGET arm-none-eabi)
    endif()
endif()
if(CMAKE_CXX_COMPILER MATCHES "clang")
    if(NOT DEFINED CMAKE_CXX_COMPILER_TARGET)
        set(CMAKE_CXX_COMPILER_TARGET arm-none-eabi)
    endif()
endif()
set(CMAKE_OBJCOPY arm-none-eabi-objcopy)
set(CMAKE_OBJDUMP arm-none-eabi-objdump)
set(CMAKE_STRIP arm-none-eabi-strip)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)
